#!/usr/bin/env node
/**
 * Bundles assets/faces/*.svg into src/faces.generated.ts as raw strings.
 *
 * The faces are self-contained SVGs whose idle animations are pure CSS
 * keyframes (no SMIL), so on web they keep animating when inlined into the
 * DOM. Metro cannot import .svg as text without an extra transformer, so we
 * pre-bake them into a TS module instead — ~50 KB total for all 21.
 *
 * Re-run after changing anything in ../avatars: `npm run gen:faces`
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const facesDir = join(root, "assets", "faces");
const out = join(root, "src", "faces.generated.ts");

const files = readdirSync(facesDir).filter((f) => f.endsWith(".svg")).sort();
const entries = files.map((file) => {
  const id = file.replace(/\.svg$/, "");
  let svg = readFileSync(join(facesDir, file), "utf8").trim();
  // Make the root <svg> fill its container: the source files carry only a
  // viewBox, and a width-less inline <svg> falls back to 300x150 in HTML.
  svg = svg.replace(/^<svg\s/, '<svg style="width:100%;height:100%;display:block;overflow:visible" ');
  return [id, svg];
});

const body = entries.map(([id, svg]) => `  ${JSON.stringify(id)}: ${JSON.stringify(svg)},`).join("\n");
writeFileSync(
  out,
  `// GENERATED by scripts/gen-faces.mjs — do not edit. Run \`npm run gen:faces\`.\n` +
    `// Source: ../avatars/faces/*.svg + ../avatars/coordinator.svg\n\n` +
    `export const FACE_SVGS: Record<string, string> = {\n${body}\n};\n\n` +
    `export const FACE_IDS: string[] = ${JSON.stringify(entries.map(([id]) => id).filter((id) => id !== "coordinator"))};\n`,
  "utf8",
);
console.log(`gen-faces: wrote ${entries.length} faces -> src/faces.generated.ts`);
