#!/usr/bin/env node
/**
 * Brand logos for connectors and other named apps, from svgl.app.
 *
 * The rule (CONTRIBUTING.md › Logos): anything that is a real product — a
 * connector, a tool an intern uses — shows its own logo, taken from
 * https://svgl.app, never a stand-in glyph.
 *
 *   npm run gen:brands                                   # assets/brands/*.svg → src/brands.generated.ts
 *   npm run gen:brands -- fetch outlook=microsoft-outlook github=github_light:github_dark
 *
 * `fetch brand=svgl-file[:svgl-dark-file]` downloads https://svgl.app/library/<file>.svg
 * into assets/brands/<brand>.svg (and <brand>_dark.svg), then regenerates.
 * Find the file names with https://api.svgl.app?search=<name>.
 *
 * Generating makes each logo safe to inline next to the others: ids are
 * prefixed with the brand (two logos' gradients can't collide), CSS `style`
 * attributes become plain SVG attributes (react-native-svg ignores inline
 * styles), and the root <svg> fills its container.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brandsDir = join(root, "assets", "brands");
const out = join(root, "src", "brands.generated.ts");

if (process.argv[2] === "fetch") {
  for (const spec of process.argv.slice(3)) {
    const [brand, files] = spec.split("=");
    if (!brand || !files || !/^[a-z0-9-]+$/.test(brand)) throw new Error(`usage: fetch brand=svgl-file[:svgl-dark-file], got ${spec}`);
    const [light, dark] = files.split(":");
    for (const [file, name] of [[light, brand], [dark, `${brand}_dark`]]) {
      if (!file) continue;
      const res = await fetch(`https://svgl.app/library/${file}.svg`);
      if (!res.ok) throw new Error(`svgl.app/library/${file}.svg: HTTP ${res.status}`);
      writeFileSync(join(brandsDir, `${name}.svg`), (await res.text()).trim() + "\n");
      console.log(`fetched ${file}.svg → assets/brands/${name}.svg`);
    }
  }
}

/** style="a:b;c:d" → a="b" c="d" (only where the attribute isn't already set). */
function inlineStyles(svg) {
  return svg.replace(/<([a-zA-Z]+)([^>]*?)\sstyle="([^"]*)"([^>]*)>/g, (_m, tag, before, style, after) => {
    const attrs = `${before}${after}`;
    const extra = style
      .split(";")
      .map((d) => d.trim())
      .filter(Boolean)
      .map((d) => d.split(":").map((s) => s.trim()))
      .filter(([k, v]) => k && v !== undefined && !new RegExp(`\\s${k}=`).test(attrs))
      .map(([k, v]) => ` ${k}="${v}"`)
      .join("");
    return `<${tag}${before}${extra}${after}>`;
  });
}

function prefixIds(svg, prefix) {
  const ids = [...svg.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  let result = svg;
  for (const id of ids) {
    const esc = id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    result = result
      .replace(new RegExp(`\\sid="${esc}"`, "g"), ` id="${prefix}-${id}"`)
      .replace(new RegExp(`url\\(#${esc}\\)`, "g"), `url(#${prefix}-${id})`)
      .replace(new RegExp(`href="#${esc}"`, "g"), `href="#${prefix}-${id}"`);
  }
  return result;
}

const files = readdirSync(brandsDir).filter((f) => f.endsWith(".svg")).sort();
const entries = files.map((file) => {
  const key = file.replace(/\.svg$/, "");
  let svg = readFileSync(join(brandsDir, file), "utf8").trim();
  svg = inlineStyles(svg);
  svg = prefixIds(svg, `brand-${key}`);
  // fill the container: drop fixed width/height on the root, keep the viewBox
  svg = svg.replace(/<svg([^>]*)>/, (_m, attrs) => `<svg${attrs.replace(/\s(width|height)="[^"]*"/g, "")} width="100%" height="100%">`);
  return [key, svg.replace(/\n\s*/g, " ")];
});

const body = entries.map(([key, svg]) => `  ${JSON.stringify(key)}: ${JSON.stringify(svg)},`).join("\n");
writeFileSync(
  out,
  `// GENERATED by scripts/gen-brands.mjs — do not edit. Run \`npm run gen:brands\`.\n` +
    `// Source: ../assets/brands/*.svg, from https://svgl.app. Logos are trademarks of their owners,\n` +
    `// shown only to identify the services the crew connects to.\n\n` +
    `export const BRAND_SVGS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`wrote ${entries.length} logos to src/brands.generated.ts`);
